travis:
  secure:
    BINSTAR_TOKEN: n/zeQZtJptiSpyDz+7qReuCZo2rh/qjbNtvxzieTmEX616axw4mb/deSxiFo925nP+9HYb/qlZTkqfs2h5LVZV/Nb7BBS8agW321BjHp/K1o5hZFY8CEY9HiA0zLoX/e9eETOQCpsSQWMtNqOzanZpY+JnqQ5mwui3EGQHcdwHQz2nvQuCx2O6TUWWNXUXqMW6aB37HwOE/jREJT7+li4juccUA8LWwnn2c1QjQNqtm1PQhvHkW0rLPy99iooE2et0zlmi4uitADO3fRl5PL5mOHIjT46GPXp1fEMdKf2xDJeBmTzw+1d2Hcf3IeL93D/lPPBA9+5IBm2ZoyyM0mD5DKSxB2k4joWsX4ApewRGx8gaLv7yWx/9VeLRaVCcaTRF628UrbJq8FBauk2sIurhx0DExP+J9OIHPe7nqWWxnWweVHK2OcTVs/DNFkLIRhp72gsKv3L2oS0JvzyJwPXL2KszGE05juKxoWgR2arasirpgHSG6pLZkVu+Z/bk8R1i/UMR6cKAw9gflI+Q9HnJtEn61fpEU4pslQFgOSRYPuLK59Kj5W4xZLQhe1EfSm9ZMF4RdhUamz1H3BnB7vcms0kC9675deC54a/g1qJzK0/bh6hnsljyeOQ1lNnh0wvTgli5aUzAhEtpG0IxQCHPmKoPh2jN8tPrXtw9FNPYk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
