travis:
  secure:
    BINSTAR_TOKEN: Ep686tOplQ77wzPftp1lBJ+P/U6SN6cOPwSxk9yLoWV6l7hj44eEgIQNRtz3wuy0MJw6I8wWN+IG89Xf1XmLMAFt6hoYDaXQKolAkjOPgqZLX0MMScjTnHrK4WonAZwu1XHKu98mMMGeOA9Gf/luZkkMmdQF1xZ1L458L0lauSrNNd0FeZBtCo7y4JCVtffNrSeXb9Tr18Y7jXjhyHVdI2yQyQVF40F5Bd/Uqhwta427maRQwgewPpiXM2mMqZQwQ+lndTguWHd3atQbFmtPDGunmEASPebtM2svYwAkwLxEo1zM0m9Zom2cVOY5BgyavdNAeFnbDZOSh7/qjcWHfkBdQDbMUh5fHT1BapkzCisTZhwTRrhoIdgctvDFp6qBDf6cFYJNlhSwad6loRe468RSQMG4YPjZZcbl9GukpUwyrLx9mGv2d0f21i50IQqWe52+8dIZ3CpbNwzsyzNUOkymBJFcdSKWlFT/mBUkdSPCIk5VCLuONZWoNZwqQC4jxEMCk2OB28ErYWny26nlu88417yJNsm7ruluwarVsJZ7e/NfLnYf4ReySF1W1dsX4zelDuXmCx2LhJ9omqwjHOMWUNKXVPvuMU/IUze4EJ7rHkbcAzYlVsE7LwkpOqqHovKjqyweIS4TkUFsdCJLoToHZ2VB4BF+OvcjStSp0es=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
