travis:
  secure:
    BINSTAR_TOKEN: lBLRMn36mlll+UP789bAc1B37M49gDe9I3I0CldhIvGDzRlrOvxUv8p9RcI+Wwog39GWuwbyOfUx3DzTNYwBYWOee94it+iSPnuN89c/3GuC+/jVrnT4KhXdD9epS7uyCWaDcpIXH2bzhXc2cjGPXauxNjLOjMzM3tk5EFKwdBQ3ylL+UYLBkVCpiOE1GBNuV741XlPQ4sF/6BKZOQ/q7WUEzwqDpT2YcDCzka0lzyr5zT0f83gUMQWTClhWnJY0ScUIJ69KQoHXQXZGuSa4aUyOywz1BiHuqSI7NgzKejoaoKn63nUKCscffPUFwN9MHn6uysLEctplqaJJzBwjq7kLKUGgkLNBVt0QsX1Dpa5GDd7jlGRqepKrQhjnShl2ZZrO8GxuMzw0XQ1OMFLu74c2cj4GOuFvFjc/52zo6AKYBXZkQYSgVgD6rWMA/s+xOl2tjXhqWyErhijGvCNBQF+ST2UEoZqU3NJ2LUBkomQY63OzG55GG8BFcQ4/vr8FgH5VyWBC3A/c482G6Etc+vIZWvqvqQG2BsuIQHbYlfL8IVSan3MvR9pu4rgoooYrFZaYcSHcdLubtomCCnTFjQUDa43u3x0lS9botPbhINMIF8ZnrJDH1CLqis2LLfTo0aCYoxlO671Cpef+YikqxXq6vJX3MlcbwLrSOczoAF0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
